site: Yunseok's Dev Blog

collections:
  pages:
    output: true
    permalink: /:name
  retrospective:
    output: true
    permalink: /:collection/:path
  daily:
    output: true
    permalink: /:collection/:path
  blogs:
    output: true
    permalink: /:collection/:path
  wikis:
    output: true
    permalink: /:path

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "retrospective"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "daily"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "blogs"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "resume"
    values:
      layout: "resume"
  - scope:
      path: ""
      type: "wikis"
    values:
      layout: "wiki"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: compressed

plugins:
  - jekyll-sitemap

autopages:
  enabled: true
  collections:
    enabled: true
    # layouts:
    #   - post.html

timezone: "Asia/Seoul"
future: true
